apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs-example
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples